INSERT INTO public.hobby (hobby) VALUES ('3D printing');
INSERT INTO public.hobby (hobby) VALUES ('Acroyoga');
INSERT INTO public.hobby (hobby) VALUES ('Acting');
INSERT INTO public.hobby (hobby) VALUES ('Aerial silk');
INSERT INTO public.hobby (hobby) VALUES ('Airbrushing');
INSERT INTO public.hobby (hobby) VALUES ('Amateur radio');
INSERT INTO public.hobby (hobby) VALUES ('Animation');
INSERT INTO public.hobby (hobby) VALUES ('Anime');
INSERT INTO public.hobby (hobby) VALUES ('Aquascaping');
INSERT INTO public.hobby (hobby) VALUES ('Art');
INSERT INTO public.hobby (hobby) VALUES ('Astrology');
INSERT INTO public.hobby (hobby) VALUES ('Baking');
INSERT INTO public.hobby (hobby) VALUES ('Barbershop Music');
INSERT INTO public.hobby (hobby) VALUES ('Baton twirling');
INSERT INTO public.hobby (hobby) VALUES ('Beatboxing');
INSERT INTO public.hobby (hobby) VALUES ('Beer');
INSERT INTO public.hobby (hobby) VALUES ('Bell ringing');
INSERT INTO public.hobby (hobby) VALUES ('Blogging');
INSERT INTO public.hobby (hobby) VALUES ('Board games');
INSERT INTO public.hobby (hobby) VALUES ('Book discussion club');
INSERT INTO public.hobby (hobby) VALUES ('Book restoration');
INSERT INTO public.hobby (hobby) VALUES ('Bowling');
INSERT INTO public.hobby (hobby) VALUES ('Brazilian jiu-jitsu');
INSERT INTO public.hobby (hobby) VALUES ('Breadmaking');
INSERT INTO public.hobby (hobby) VALUES ('Bullet journaling');
INSERT INTO public.hobby (hobby) VALUES ('Calligraphy');
INSERT INTO public.hobby (hobby) VALUES ('Candle making');
INSERT INTO public.hobby (hobby) VALUES ('Candy making');
INSERT INTO public.hobby (hobby) VALUES ('Car fixing & building');
INSERT INTO public.hobby (hobby) VALUES ('Card games');
INSERT INTO public.hobby (hobby) VALUES ('Cardistry');
INSERT INTO public.hobby (hobby) VALUES ('Ceramics');
INSERT INTO public.hobby (hobby) VALUES ('Online chating');
INSERT INTO public.hobby (hobby) VALUES ('Cheesemaking');
INSERT INTO public.hobby (hobby) VALUES ('Chess');
INSERT INTO public.hobby (hobby) VALUES ('Cleaning');
INSERT INTO public.hobby (hobby) VALUES ('Clothing');
INSERT INTO public.hobby (hobby) VALUES ('Coffee roasting');
INSERT INTO public.hobby (hobby) VALUES ('Collecting');
INSERT INTO public.hobby (hobby) VALUES ('Coloring');
INSERT INTO public.hobby (hobby) VALUES ('Communication');
INSERT INTO public.hobby (hobby) VALUES ('Community activism');
INSERT INTO public.hobby (hobby) VALUES ('Computer programming');
INSERT INTO public.hobby (hobby) VALUES ('Confectionery');
INSERT INTO public.hobby (hobby) VALUES ('Constructed language');
INSERT INTO public.hobby (hobby) VALUES ('Construction');
INSERT INTO public.hobby (hobby) VALUES ('Cooking');
INSERT INTO public.hobby (hobby) VALUES ('Cosplaying');
INSERT INTO public.hobby (hobby) VALUES ('Couch surfing');
INSERT INTO public.hobby (hobby) VALUES ('Couponing');
INSERT INTO public.hobby (hobby) VALUES ('Craft');
INSERT INTO public.hobby (hobby) VALUES ('Creative writing');
INSERT INTO public.hobby (hobby) VALUES ('Crocheting');
INSERT INTO public.hobby (hobby) VALUES ('Cross-stitch');
INSERT INTO public.hobby (hobby) VALUES ('Crossword puzzles');
INSERT INTO public.hobby (hobby) VALUES ('Cryptography');
INSERT INTO public.hobby (hobby) VALUES ('Cue sports');
INSERT INTO public.hobby (hobby) VALUES ('Dance');
INSERT INTO public.hobby (hobby) VALUES ('Decorating');
INSERT INTO public.hobby (hobby) VALUES ('Digital art');
INSERT INTO public.hobby (hobby) VALUES ('Dining');
INSERT INTO public.hobby (hobby) VALUES ('Diorama');
INSERT INTO public.hobby (hobby) VALUES ('Distro-hopping');
INSERT INTO public.hobby (hobby) VALUES ('Diving');
INSERT INTO public.hobby (hobby) VALUES ('Djembe');
INSERT INTO public.hobby (hobby) VALUES ('DJing');
INSERT INTO public.hobby (hobby) VALUES ('Do it yourself');
INSERT INTO public.hobby (hobby) VALUES ('Drama');
INSERT INTO public.hobby (hobby) VALUES ('Drawing');
INSERT INTO public.hobby (hobby) VALUES ('Drink mixing');
INSERT INTO public.hobby (hobby) VALUES ('Electronic games');
INSERT INTO public.hobby (hobby) VALUES ('Electronics');
INSERT INTO public.hobby (hobby) VALUES ('Embroidery');
INSERT INTO public.hobby (hobby) VALUES ('Engraving');
INSERT INTO public.hobby (hobby) VALUES ('Entertaining');
INSERT INTO public.hobby (hobby) VALUES ('Experimenting');
INSERT INTO public.hobby (hobby) VALUES ('Fantasy sport]');
INSERT INTO public.hobby (hobby) VALUES ('Fashion');
INSERT INTO public.hobby (hobby) VALUES ('Fashion design');
INSERT INTO public.hobby (hobby) VALUES ('Feng shui');
INSERT INTO public.hobby (hobby) VALUES ('Filmmaking');
INSERT INTO public.hobby (hobby) VALUES ('Fingerpainting');
INSERT INTO public.hobby (hobby) VALUES ('Fishfarming');
INSERT INTO public.hobby (hobby) VALUES ('Fishkeeping');
INSERT INTO public.hobby (hobby) VALUES ('Flower arranging');
INSERT INTO public.hobby (hobby) VALUES ('Fly tying');
INSERT INTO public.hobby (hobby) VALUES ('Foreign language learning');
INSERT INTO public.hobby (hobby) VALUES ('Furniture building');
INSERT INTO public.hobby (hobby) VALUES ('Gaming');
INSERT INTO public.hobby (hobby) VALUES ('Genealogy');
INSERT INTO public.hobby (hobby) VALUES ('Gingerbread house making');
INSERT INTO public.hobby (hobby) VALUES ('Giving advice');
INSERT INTO public.hobby (hobby) VALUES ('Glassblowing');
INSERT INTO public.hobby (hobby) VALUES ('Gardening');
INSERT INTO public.hobby (hobby) VALUES ('Gongfu tea');
INSERT INTO public.hobby (hobby) VALUES ('Graphic design');
INSERT INTO public.hobby (hobby) VALUES ('Gunsmithing');
INSERT INTO public.hobby (hobby) VALUES ('Hacking');
INSERT INTO public.hobby (hobby) VALUES ('Computer hardware');
INSERT INTO public.hobby (hobby) VALUES ('Herp keeping');
INSERT INTO public.hobby (hobby) VALUES ('Home improvement');
INSERT INTO public.hobby (hobby) VALUES ('Homebrewing');
INSERT INTO public.hobby (hobby) VALUES ('Houseplant care');
INSERT INTO public.hobby (hobby) VALUES ('Hula hooping');
INSERT INTO public.hobby (hobby) VALUES ('Humor');
INSERT INTO public.hobby (hobby) VALUES ('Hydroponics');
INSERT INTO public.hobby (hobby) VALUES ('Ice skating');
INSERT INTO public.hobby (hobby) VALUES ('Inventing');
INSERT INTO public.hobby (hobby) VALUES ('Jewelry making');
INSERT INTO public.hobby (hobby) VALUES ('Jigsaw puzzle');
INSERT INTO public.hobby (hobby) VALUES ('Journaling');
INSERT INTO public.hobby (hobby) VALUES ('Juggling');
INSERT INTO public.hobby (hobby) VALUES ('Karaoke');
INSERT INTO public.hobby (hobby) VALUES ('Karate');
INSERT INTO public.hobby (hobby) VALUES ('Kendama');
INSERT INTO public.hobby (hobby) VALUES ('Knife making');
INSERT INTO public.hobby (hobby) VALUES ('Knitting');
INSERT INTO public.hobby (hobby) VALUES ('Knot tying');
INSERT INTO public.hobby (hobby) VALUES ('Kombucha brewing');
INSERT INTO public.hobby (hobby) VALUES ('Kung fu');
INSERT INTO public.hobby (hobby) VALUES ('Lace making');
INSERT INTO public.hobby (hobby) VALUES ('Lapidary');
INSERT INTO public.hobby (hobby) VALUES ('Leather crafting');
INSERT INTO public.hobby (hobby) VALUES ('Lego building');
INSERT INTO public.hobby (hobby) VALUES ('Livestreaming');
INSERT INTO public.hobby (hobby) VALUES ('Listening to music');
INSERT INTO public.hobby (hobby) VALUES ('Listening to podcasts');
INSERT INTO public.hobby (hobby) VALUES ('Lock picking');
INSERT INTO public.hobby (hobby) VALUES ('Machining');
INSERT INTO public.hobby (hobby) VALUES ('Macrame');
INSERT INTO public.hobby (hobby) VALUES ('Magic (illusion)');
INSERT INTO public.hobby (hobby) VALUES ('Makeup');
INSERT INTO public.hobby (hobby) VALUES ('Manga');
INSERT INTO public.hobby (hobby) VALUES ('Massaging');
INSERT INTO public.hobby (hobby) VALUES ('Mazes');
INSERT INTO public.hobby (hobby) VALUES ('Mechanics');
INSERT INTO public.hobby (hobby) VALUES ('Meditation');
INSERT INTO public.hobby (hobby) VALUES ('Memory training');
INSERT INTO public.hobby (hobby) VALUES ('Metalworking');
INSERT INTO public.hobby (hobby) VALUES ('Miniature art');
INSERT INTO public.hobby (hobby) VALUES ('Minimalism');
INSERT INTO public.hobby (hobby) VALUES ('Model building');
INSERT INTO public.hobby (hobby) VALUES ('Modeling');
INSERT INTO public.hobby (hobby) VALUES ('Model engineering');
INSERT INTO public.hobby (hobby) VALUES ('Music');
INSERT INTO public.hobby (hobby) VALUES ('Nail art');
INSERT INTO public.hobby (hobby) VALUES ('Needlepoint');
INSERT INTO public.hobby (hobby) VALUES ('Origami');
INSERT INTO public.hobby (hobby) VALUES ('Painting');
INSERT INTO public.hobby (hobby) VALUES ('Palmistry');
INSERT INTO public.hobby (hobby) VALUES ('Pen Spinning');
INSERT INTO public.hobby (hobby) VALUES ('Performance');
INSERT INTO public.hobby (hobby) VALUES ('Pet');
INSERT INTO public.hobby (hobby) VALUES ('Pet adoption & fostering');
INSERT INTO public.hobby (hobby) VALUES ('Pet sitting');
INSERT INTO public.hobby (hobby) VALUES ('Philately');
INSERT INTO public.hobby (hobby) VALUES ('Photography');
INSERT INTO public.hobby (hobby) VALUES ('Pilates');
INSERT INTO public.hobby (hobby) VALUES ('Planning');
INSERT INTO public.hobby (hobby) VALUES ('Plastic art');
INSERT INTO public.hobby (hobby) VALUES ('Playing musical instruments');
INSERT INTO public.hobby (hobby) VALUES ('Poetry');
INSERT INTO public.hobby (hobby) VALUES ('Poi');
INSERT INTO public.hobby (hobby) VALUES ('Pole dancing');
INSERT INTO public.hobby (hobby) VALUES ('Postcrossing');
INSERT INTO public.hobby (hobby) VALUES ('Pottery');
INSERT INTO public.hobby (hobby) VALUES ('Power Nap');
INSERT INTO public.hobby (hobby) VALUES ('Practical jokes');
INSERT INTO public.hobby (hobby) VALUES ('Pressed flower craft');
INSERT INTO public.hobby (hobby) VALUES ('Proofreading and editing');
INSERT INTO public.hobby (hobby) VALUES ('Proverbs');
INSERT INTO public.hobby (hobby) VALUES ('Public speaking');
INSERT INTO public.hobby (hobby) VALUES ('Puppetry');
INSERT INTO public.hobby (hobby) VALUES ('Puzzle]');
INSERT INTO public.hobby (hobby) VALUES ('Pyrography');
INSERT INTO public.hobby (hobby) VALUES ('Quilling');
INSERT INTO public.hobby (hobby) VALUES ('Quilting');
INSERT INTO public.hobby (hobby) VALUES ('Quizzes');
INSERT INTO public.hobby (hobby) VALUES ('Radio-controlled model');
INSERT INTO public.hobby (hobby) VALUES ('Rail transport modeling');
INSERT INTO public.hobby (hobby) VALUES ('Rapping');
INSERT INTO public.hobby (hobby) VALUES ('Reading');
INSERT INTO public.hobby (hobby) VALUES ('Recipe creation');
INSERT INTO public.hobby (hobby) VALUES ('Refinishing');
INSERT INTO public.hobby (hobby) VALUES ('Reiki');
INSERT INTO public.hobby (hobby) VALUES ('Reviewing Gadgets');
INSERT INTO public.hobby (hobby) VALUES ('Robot combat');
INSERT INTO public.hobby (hobby) VALUES ('Rubik''s Cube');
INSERT INTO public.hobby (hobby) VALUES ('Scrapbooking');
INSERT INTO public.hobby (hobby) VALUES ('Scuba Diving');
INSERT INTO public.hobby (hobby) VALUES ('culpting');
INSERT INTO public.hobby (hobby) VALUES ('Sewing');
INSERT INTO public.hobby (hobby) VALUES ('Shoemaking');
INSERT INTO public.hobby (hobby) VALUES ('Singing');
INSERT INTO public.hobby (hobby) VALUES ('Sketching');
INSERT INTO public.hobby (hobby) VALUES ('Skipping rope');
INSERT INTO public.hobby (hobby) VALUES ('Slot car');
INSERT INTO public.hobby (hobby) VALUES ('Soapmaking');
INSERT INTO public.hobby (hobby) VALUES ('Social media');
INSERT INTO public.hobby (hobby) VALUES ('Spreadsheets');
INSERT INTO public.hobby (hobby) VALUES ('Stamp collecting');
INSERT INTO public.hobby (hobby) VALUES ('Stand-up comedy');
INSERT INTO public.hobby (hobby) VALUES ('Storytelling');
INSERT INTO public.hobby (hobby) VALUES ('Striptease');
INSERT INTO public.hobby (hobby) VALUES ('Sudoku');
INSERT INTO public.hobby (hobby) VALUES ('Talking');
INSERT INTO public.hobby (hobby) VALUES ('Tapestry');
INSERT INTO public.hobby (hobby) VALUES ('Tarot');
INSERT INTO public.hobby (hobby) VALUES ('Tatebanko');
INSERT INTO public.hobby (hobby) VALUES ('Tattoo]]i');
INSERT INTO public.hobby (hobby) VALUES ('Taxidermy');
INSERT INTO public.hobby (hobby) VALUES ('Telling jokes');
INSERT INTO public.hobby (hobby) VALUES ('Charity shop');
INSERT INTO public.hobby (hobby) VALUES ('Upcycling');
INSERT INTO public.hobby (hobby) VALUES ('Video editing');
INSERT INTO public.hobby (hobby) VALUES ('Video game development');
INSERT INTO public.hobby (hobby) VALUES ('Video gaming');
INSERT INTO public.hobby (hobby) VALUES ('Videography');
INSERT INTO public.hobby (hobby) VALUES ('VR Gaming');
INSERT INTO public.hobby (hobby) VALUES ('Wargaming');
INSERT INTO public.hobby (hobby) VALUES ('Watch making');
INSERT INTO public.hobby (hobby) VALUES ('Documentary film');
INSERT INTO public.hobby (hobby) VALUES ('Movies');
INSERT INTO public.hobby (hobby) VALUES ('Watching television');
INSERT INTO public.hobby (hobby) VALUES ('Wax sealing');
INSERT INTO public.hobby (hobby) VALUES ('Waxing');
INSERT INTO public.hobby (hobby) VALUES ('Weaving');
INSERT INTO public.hobby (hobby) VALUES ('Webtoon]]i');
INSERT INTO public.hobby (hobby) VALUES ('Weight training');
INSERT INTO public.hobby (hobby) VALUES ('Welding');
INSERT INTO public.hobby (hobby) VALUES ('Whisky');
INSERT INTO public.hobby (hobby) VALUES ('Whittling');
INSERT INTO public.hobby (hobby) VALUES ('Wikipedia editing');
INSERT INTO public.hobby (hobby) VALUES ('Wine tasting');
INSERT INTO public.hobby (hobby) VALUES ('Winemaking');
INSERT INTO public.hobby (hobby) VALUES ('Witchcraft');
INSERT INTO public.hobby (hobby) VALUES ('Wood carving');
INSERT INTO public.hobby (hobby) VALUES ('Woodworking');
INSERT INTO public.hobby (hobby) VALUES ('Word searches');
INSERT INTO public.hobby (hobby) VALUES ('Worldbuilding');
INSERT INTO public.hobby (hobby) VALUES ('Writing');
INSERT INTO public.hobby (hobby) VALUES ('Writing music');
INSERT INTO public.hobby (hobby) VALUES ('Yo-yoing');
INSERT INTO public.hobby (hobby) VALUES ('Yoga');
INSERT INTO public.hobby (hobby) VALUES ('Zumba');

SELECT * FROM public.hobby;
